### ISSUE TITLE
io_uring implementation instead of tokio?

### ISSUE THREAD

**Issue by hiqsociety** [dpbriggs/redis-oxide#8]
possible to check out https://github.com/bytedance/monoio
?

**Comment by dpbriggs** [comment]
That's something I looked into in the past and it wasn't ready yet. I might make a branch and check that out. I'd prefer to stick with pure Tokio if I could

**Comment by hiqsociety** [comment]
checking the benchmark tokio is obsolete. do go with io_uring monoio bytedance if possible.

the only thing missing from this redis oxide is publish subscribe i guess, else great work!

**Comment by dpbriggs** [comment]
Definitely lots of work left to do :p

The [README](https://github.com/dpbriggs/redis-oxide#basic-datastructures) describes some of the other missing bits. There's three major perf issues at the moment:

- Saving the database to disk is done very naively. We locked the entire db and serialize it
- Major synchronization headaches across each thread
- Unnecessary cloning/juggling of ops internally
